# Generated by Django 2.1.5 on 2021-01-06 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_review_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='review time'),
        ),
    ]
