# Generated by Django 2.1.5 on 2021-01-07 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20210106_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='posted time'),
        ),
    ]
