# Generated by Django 3.1.5 on 2021-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210107_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_check',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place_type',
            field=models.CharField(default='Restaurant', max_length=200),
        ),
    ]
