# Generated by Django 2.1.5 on 2021-01-06 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210106_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='review time'),
        ),
    ]
