# Generated by Django 3.1.5 on 2021-01-09 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210106_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
